FROM nginx:stable-alpine

MAINTAINER authors="cipchk <cipchk@qq.com>"

WORKDIR /usr/src

RUN git clone --depth 1 --branch gh-pages  http://comail:8888/tfs/Cityocean/CO.Platform/_git/co-libs dist \
    && sed -i 's/\/delon\//\//g' /usr/src/dist/index.html \
    && sed -i 's/\/delon\//\//g' /usr/src/dist/404.html

COPY _nginx _nginx
